# Generated by Django 2.1.9 on 2020-07-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_entry_short_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='short_text',
            field=models.CharField(blank=True, default='', max_length=350, null=True, verbose_name='Краткая информация'),
        ),
    ]
